#### 5.1. Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B. Вычислите, по возможности не используя программирование: (5E)-1 где Е – единичная матрица размера 5х5.

In [5]:
import numpy as np

In [8]:
E = np.identity(5)
print(E)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


$E = A*A^-1$

In [9]:
E_5 = E*5
print(E_5)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [10]:
E_5_inv = np.linalg.inv(E_5)
print(E_5_inv)

[[0.2 0.  0.  0.  0. ]
 [0.  0.2 0.  0.  0. ]
 [0.  0.  0.2 0.  0. ]
 [0.  0.  0.  0.2 0. ]
 [0.  0.  0.  0.  0.2]]


In [13]:
np.dot(E_5_inv, E_5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.dot(E_5, E_5_inv)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 5.2. Вычислите определитель: 
#### [1, 2, 3
#### 4, 0, 6
#### 7, 8, 9]

In [16]:
a = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [20]:
# Находим определитель матрицы:

det_a = 1*(0*9 - 6*8) - 2*(4*9 - 6*7) + 3*(4*8 - 0*7)
print(det_a)

60


#### 5.3.1. Вычислите матрицу, обратную данной:
#### [1, 2, 3
#### 4, 0, 6
#### 7, 8, 9]

In [27]:
B = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
print(B)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [28]:
# Находим определитель матрицы:

det_B = 1*(0*9 - 6*8) - 2*(4*9 - 6*7) + 3*(4*8 - 0*7)
print(det_B)

60


In [29]:
# Теперь находим матрицу миноров. 
# Для этого найдем миноры элементов (их должно получиться 9) и запишем в новую матрицу:

b_1 = 0*9 - 6*8
b_2 = 4*9 - 6*7
b_3 = 4*8 - 0*7
b_4 = 2*9 - 3*8
b_5 = 1*9 - 3*7
b_6 = 1*8 - 2*7
b_7 = 2*6 - 3*0
b_8 = 1*6 - 3*4
b_9 = 1*0 - 2*4

In [30]:
M = np.array([[b_1, b_2, b_3], [b_4, b_5, b_6], [b_7, b_8, b_9]])
print(M)

[[-48  -6  32]
 [ -6 -12  -6]
 [ 12  -6  -8]]


In [32]:
# Далее находим матрицу алгебраических дополнений:

B_d = np.array([[b_1, -b_2, b_3], [-b_4, b_5, -b_6], [b_7, -b_8, b_9]])
print(B_d)

[[-48   6  32]
 [  6 -12   6]
 [ 12   6  -8]]


In [25]:
# Находим транспонированную матрицу алгебраических дополнений:

B_t = B.transpose()
print(B_t)

[[-48   6  12]
 [  6 -12   6]
 [ 32   6  -8]]


#### 5.3.2. Приведите пример матрицы 4х4, ранг которой равен 1.

In [37]:
a = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
print(a)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


In [39]:
# Возьмем две произвольные строки, например, 2-ю и 4-ю, два произвольных столбца, например, 3-й и 4-й, 
# и числа, находящиеся на их пересечении запишем в минор второго порядка:

M_2 = np.array([[2, 2], [4, 4]])
print(M_2)

[[2 2]
 [4 4]]


In [40]:
m_2 = 2*4 - 2*4
print(m_2)

0


In [41]:
# Если проделать аналогичные действия с еще несколькими минорами второго порядка, то получится, что все миноры будут равны 0.
# Следовательно, это матрица с рангом = 1

#### 5.4. Вычислите скалярное произведение двух векторов: (1, 5)  и  (2, 8)

In [44]:
a = np.array([1, 5], float)
b = np.array([2, 8], float)
print(a*b)

[ 2. 40.]


In [45]:
np.dot(a, b)

42.0

#### 5.5 Вычислите смешанное произведение трех векторов: (1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 


In [59]:
A = np.array([[1, 5, 0], [2, 8, 7], [7, 1.5, 3]])
print(A)

[[1.  5.  0. ]
 [2.  8.  7. ]
 [7.  1.5 3. ]]


In [60]:
# Ищем определитель матрицы:

det_a = 1*(8*3 - 7*1.5) - 5*(2*3 - 7*7) + 0*(2*1.5 - 8*7)
print(det_a)

228.5
